DROP TRIGGER IF EXISTS update_password_timestamp;
DROP TABLE IF EXISTS Password;
DROP TRIGGER IF EXISTS update_user_timestamp;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username varchar(256) NOT NULL,
    Email varchar(256) NOT NULL,
    Password varchar(256) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Password (
    PasswordID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title varchar(256) NOT NULL,  
    Username varchar(256) NOT NULL, 
    EncryptedPassword varchar(256) NOT NULL, 
    FK_UserID INTEGER NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FK_UserID) REFERENCES User(UserID)
);

CREATE TRIGGER update_user_timestamp
AFTER UPDATE ON User
FOR EACH ROW
BEGIN
    UPDATE User
    SET UpdatedAt = CURRENT_TIMESTAMP
    WHERE UserID = OLD.UserID;
END;

CREATE TRIGGER update_password_timestamp
AFTER UPDATE ON Password
FOR EACH ROW
BEGIN
    UPDATE Password
    SET UpdatedAt = CURRENT_TIMESTAMP
    WHERE PasswordID = OLD.PasswordID;
END;